import Header from './Header';
import Footer from './Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
      <Header/>
      <button>Adicionar</button>
      <h2>Não compre nessa loja. Não se renda ao capitalismo.</h2>
      {/* <Footer/> */}
      </body>
    </html>
  )
}
