import Header from './Header';
import Footer from './Footer'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="layout">
        <Header/>
        <br/>
          {children}
        <Footer/>
      </body>
    </html>
  )
}
